
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
    - name: Connect to Tailscale
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
    - name: Pull changes and build on remote server
      run: |
        ssh -p 2222 -vvv ${{secrets.USER}}@${{secrets.HOST}} "./nginxssl.sh"

    - name: Disconnect TailScale
      run: |
        sudo tailscale logout
