name: CI/CD
on:
  push:
    branches:
    - testing

jobs:
  build:
    runs-on: tailscale/tailscale
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 2222 ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Pull changes and build on remote server
      run: |
        ssh -p 2222 ${{secrets.USERNAME}}@${{secrets.HOST}} "./nginxssl.sh" 

    - name: Disconnect TailScale
      run: |
        sudo tailscale logout
